p1:
	gcc part1.c -o p1
	./p1 BACKING_STORE.bin addresses.txt

p2lru:
	gcc part2.c -o p2
	./p2 BACKING_STORE.bin addresses.txt -p 1

p2sc:
	gcc part2.c -o p2
	./p2 BACKING_STORE.bin addresses.txt -p 0

clean:
	rm -f p1 p2


